version: '3'

networks:
    default:
        external:
            name: network
    backend:
    
services:
    plugin-nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./plugin:/app
            - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx/
        environment:
            - VIRTUAL_HOST=dev2.zima.kg
            - LETSENCRYPT_HOST=dev2.zima.kg
            - LETSENCRYPT_EMAIL=igor@zima.kg
        depends_on:
            - plugin-php-fpm
        networks:
            - backend
            
    plugin-php-fpm:
        build:
            context: ./docker/development/
            dockerfile: php-fpm.docker
        container_name: php-fpm
        volumes:
            - ./plugin:/app
        depends_on:
            - db
        networks:
            - backend
    
    plugin-php-cli:
        build:
            context: ./docker/development/
            dockerfile: php-cli.docker
        container_name: php-cli
        volumes:
            - ./plugin:/app
            - composer:/root/.composer/cache
        depends_on:
            - db
        networks:
            - backend

    db:
        image: postgres:12.2-alpine
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./postgres/dump:/dump
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DATABASE}
        ports:
            - "54321:5432"
        networks:
            - backend
            
volumes:
    db-data:
    composer: